### ISSUE TITLE
Is this repository still maintained?

### ISSUE THREAD

**Issue by reime005** [adgatemedia/adgate-rewards-ios-sdk#1]
I integrated the SDK successfully, but ran into a segmentation fault. This may have something to do with the SDKUrls object

**Comment by eblanshey** [comment]
Hi @reime005, sorry to hear you're having this issue. We actually have a major update to our SDK that we will be releasing very soon, but meanwhile I will have our team take a look at this for a bugfix update. If you have any additional details on how we can replicate this, that would be fantastic!

**Comment by eblanshey** [comment]
Hi @reime005, additional details on how to reproduce the issue would be appreciated, as it's working on our end.

**Comment by eblanshey** [comment]
As we have not had a response from you, and the [new SDK](https://github.com/adgatemedia/adgate-rewards-ios-sdk/releases) is released, I am closing this issue.
